#!/usr/bin/env bash
set -e
# go to the root of the repository
cd "$(git rev-parse --show-toplevel)"

#check if just is installed
if ! command -v just &> /dev/null
then
  bun add -g rust-just
fi
# update the wasm file
just wasm

git add WASM/static/*.wasm
